VERSION 0.6
FROM golang:1.15-alpine3.13
WORKDIR /webserver

deps:
    COPY go.mod go.sum ./
    RUN go mod download
    SAVE ARTIFACT go.mod AS LOCAL go.mod
    SAVE ARTIFACT go.sum AS LOCAL go.sum

build:
    FROM +deps
    COPY cmd/server/main.go .
    RUN go build -o build/webserver main.go
    SAVE ARTIFACT build/webserver /webserver

docker:
    COPY +build/webserver .
    ENTRYPOINT ["/webserver/webserver"]
    EXPOSE 8080
    SAVE IMAGE --push agbell/cloudservices/webserver

test-deps:
    FROM earthly/dind
    RUN apk add curl ripgrep

test:
    FROM +test-deps
    COPY test.sh .
    WITH DOCKER --load agbell/cloudservices/webserver=+docker
        RUN  docker run -d -p 8080:8080 agbell/cloudservices/webserver && \
                ./test.sh
    END