#!/usr/bin/env bash

INIT_LOCATION="$0"


## External

list(){ # This list you are seeing now
    ./util/list.awk "$INIT_LOCATION"
}

unset-functions(){ # Unset all these functions
    script=$(./util/unset.awk "$INIT_LOCATION")
    eval "$script"
}

protobuf-generate(){
    protoc activity-log/api/v1/*.proto \
    --go_out=. \
    --go_opt=paths=source_relative \
    --go-grpc_out=. \
    --go-grpc_opt=paths=source_relative \
    --proto_path=.
}

start-activity-log()(
    cd activity-log || exit
    go run cmd/server/main.go
)