VERSION 0.6
FROM golang:1.15-alpine3.13
WORKDIR /activityclient

deps:
    COPY go.mod ./
    RUN go mod download
    SAVE ARTIFACT go.mod AS LOCAL go.mod

build:
    FROM +deps
    COPY . .
    RUN go build -o build/activityclient cmd/client/main.go
    SAVE ARTIFACT build/activityclient /activityclient

test-deps:
    FROM earthly/dind
    RUN apk add curl ripgrep

test:
    FROM +test-deps
    COPY +build/activityclient ./activityclient
    COPY test.sh .
    WITH DOCKER --load agbell/cloudservices/activityserver=github.com/adamgordonbell/cloudservices/activity-log+docker
        RUN  docker run -d -p 8080:8080 agbell/cloudservices/activityserver && \
                ./test.sh
    END