name: Go

on:
  push:
   branches:
      - 'main'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:
  create:
    tags:
      - '*'

jobs:
  ActivityLog:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
      - uses: actions/checkout@v2
      - name: Generate Certs
        run:  earthly -P ./activity-log+certs
      - name: Run End to End ActivityLog tests
        run:  earthly -P ./activity-log+test
  ActivityClient:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
      - uses: actions/checkout@v2
      - name: Generate Certs
        run:  earthly -P ./activity-log+certs
      - name: Run End to End ActivityClient tests
        run:  earthly -P ./activity-client+test
     