name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  WebServer:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
      - uses: actions/checkout@v2
      - name: Run End to End WebServer tests
        run:  earthly -P ./web-server+test
  ActivityLog:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
      - uses: actions/checkout@v2
      - name: Run End to End ActivityLog tests
        run:  earthly -P ./activity-log+test
  ActivityClient:
    runs-on: ubuntu-latest
    steps:
      - uses: earthly/actions/setup-earthly@v1
      - uses: actions/checkout@v2
      - name: Run End to End ActivityClient tests
        run:  earthly -P +ac-test
     